const fs=require('fs');
const s=fs.readFileSync('frontend/src/mock/dbStore.ts','utf8');
const lines=s.split('\n');
const idx=lines.findIndex(l=>l.includes("c20'"));
console.log('c20 line:',idx+1);
console.log('around:');
console.log(lines.slice(idx-2,idx+4).join('\n'));
console.log('---');
const sidx=lines.findIndex(l=>l.includes("s_new_15"));
console.log('s_new_15 line:',sidx+1);
console.log('around:');
console.log(lines.slice(sidx-2,sidx+4).join('\n'));